version: '3.3'
services:
    rdtclient:
      container_name: "rdtclient"
      environment:
        - "PGID=1000"
        - "PUID=1000"
      volumes:
        - "/etc/localtime:/etc/localtime:ro"
        - "/mnt:/mnt"
        - "/opt/rdtclient/data:/data"
        - "/opt/rdtclient/data/db:/data/db"
      image: "rogerfar/rdtclient"
      restart: "unless-stopped"
      ports:
        - '6500:6500'
